name: pymc3-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.*
  - arviz==0.11.*
  - black
  - conda
  - ipython==7.26.*
  - isort
  - jupyterlab==3.1.*
  - jupyterlab_code_formatter==1.4.*
  - graphviz==2.48.*
  - matplotlib==3.4.*
  - mypy
  - nbconvert==6.1.*
  - nbqa
  - numpy==1.21.*
  - pandas==1.3.*
  - plotnine==0.8.*
  - pre-commit
  - pymc3==3.11.*
  - python-graphviz==0.17.*
  - seaborn==0.11.*
  - watermark==2.2.*
