name: pymc3-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.*
  - arviz==0.11.*
  - black
  - conda
  - ipython
  - isort
  - jupyterlab==3.2.*
  - jupyterlab_code_formatter
  - graphviz
  - matplotlib
  - mypy
  - nbconvert
  - nbqa
  - numpy==1.21.*
  - pandas==1.3.*
  - plotnine==0.8.*
  - pre-commit
  - pyjanitor
  - pymc3==3.11.*
  - seaborn
  - watermark
